### ISSUE TITLE
Error: Failed to initiate extension 'encryptcontent': 'module' object has no attribute 'makeExtension'

### ISSUE THREAD

**Issue by simchanu29** [CoinK0in/mkdocs-encryptcontent-plugin#1]
Hi, 

When I try to build my wiki with the following configuration for the extensions : 

```
markdown_extensions:
    - encryptcontent:
        global_password: 'passwd'
    - markdown_include.include:
        base_path: docs
```

I get the following error : 

```
ERROR   -  Config value: 'markdown_extensions'. Error: Failed to initiate extension 'encryptcontent': 'module' object has no attribute 'makeExtension'

Aborted with 1 Configuration Errors!
```

Do you have any idea where it might come from ?

I use Python `2.7` with mkdocs `1.0.4` . mkdocs-encryptcontent-plugin is in version `0.0.2`.

**Comment by simchanu29** [comment]
It was a dumb mistake from my configuration file

`encryptcontent` needs to be inside plugin instead of `markdown_extensions`.
```
markdown_extensions:
    - markdown_include.include:
        base_path: docs
        
plugins: 
    - search
    - encryptcontent:
        global_password: 'passwd
```

I close the issue
