### ISSUE TITLE
Bug: remember_password option is not working properly because of URL encoding

### ISSUE THREAD

**Issue by anthares101** [CoinK0in/mkdocs-encryptcontent-plugin#16]
Hi! I have tried the `remember_password ` option to allow users to remember the password to the pages in my site (It is a write ups site so i don´t really care about the passwords visibility in the cookie).

The thing is that using this configuration in the plugins section:
```yaml
plugins:
  - section-index
  - search
  - encryptcontent:
      password_button: True
      password_button_text: 'Unlock'
      title_prefix: ''
      summary: 'This content is protected'
      placeholder: ''
      encryption_info_message: 'Use the root flag as password'
      tag_encrypted_page: True
      encrypted_something:
            md-nav md-nav--secondary: [nav, class]
```
I launched my site locally with `mkdocs serve` and cookies are only created when I press enter . Maybe I missed something but after reading the README again I can't really see nothing more to setup.

Also i noticed that the cookie is URL encoded and if the password has for example a `{` It will fail to decrypt.

**Comment by CoinK0in** [comment]
Hi, thanks for you feedback :)

First, about le password button, described here https://github.com/CoinK0in/mkdocs-encryptcontent-plugin#add-button there is no cookie creation. When enable, it allows to decrypt the content **without creating** a cookie (if remember password feature is activated).

Honestly I can't remember why I didn't add the process of creating the cookie with the button, but I don't think that's a problem. I would make an addition on this part so that if the functionality of remembering the password to activated the button allows to "at least" create the cookie of the local page. (Button cannot be use to create generic cookie a.k.a `path=/`)

I realize that the documentation is not necessarily clear to everyone, so if you have any suggestions for improving it please do not hesitate.

Regarding your remark on the special character and the encoding of the password in a cookie, it seems to be because of my use of the `encodeURIComponent()` which is clearly not good. I will also modify this part which from my point of view is much more problematic.

**Comment by anthares101** [comment]
Hi!

Thanks that changes would be awesome! About the documentation, in this case I think that it is easier for the user to find that the button won't create a cookie if the information is in the `remember_password` section because normally is the part you look for first in this situation.

As a suggestion for the cookie encoding problem, an easy fix could be using the `encodeURIComponent()` for encryption too to avoid this password missmatch.

**Comment by CoinK0in** [comment]
Hey, sorry for the delay. I took the time to make a few other changes that I had put aside for a while.

The [version 1.2.1](https://github.com/CoinK0in/mkdocs-encryptcontent-plugin/releases/tag/1.2.1) that I just published adds the creation of the default cookie with the button, when the "remember pawword" functionality is enabled. 

I also fixed the special character issue when reloaded from a cookie.

Here is which will have to answer to the different points ascent.

I also enabled some functionality by default and reworked the documentation a bit.

Thank you again for your comments.
All your feedback is welcome :)

**Comment by anthares101** [comment]
Hey! Thanks a lot for the changes. I tested them and worked perfectly :D Just one thing i noticed, when using this config:
```
theme:
  name: material
  features:
    - navigation.instant
```
Looks like the encrypted pages are not able to be decrypted as they should (Reload needed). Maybe using the `reload_scripts` option can help but i couldn't test it.
