### ISSUE TITLE
Encryption add - fails on Github.io host

### ISSUE THREAD

**Issue by JamesRivers** [CoinK0in/mkdocs-encryptcontent-plugin#19]
Hi, added the following to the mkdocs.yml after I installed the plugin. 

```yaml
plugins:
    - search: {}
    - encryptcontent:
        global_password: 'password!'
        remember_password: True
        default_expire_dalay: 12
```
Global encryption works well on dev environment via mkdocs serve. 

But once pushed to github with gh-pages, the passwod authentication never works.

**Comment by JamesRivers** [comment]
@CoinK0in sure no problem thanks for getting back to me..

- mkdocs 1.2.3
- mkdocs-encryptcontent-plugin 2.0.0
- mkdocs material additonal plugin
- mkdocs.yml
```yml
site_name: site name
nav:
 - Home: index.md
 - About: about.md

theme:
  name: material
  logo: assets/logo.png
  favicon: assets/favicon.png
  palette:
    scheme: slate
    primary: blue

plugins:
    - search: {}
    - encryptcontent:
        global_password: 'Password12345!'
        remember_password: True
        default_expire_dalay: 12
        password_button: True
        password_button_text: 'login'
```
- push to gh pages via a `mkdocs gh-deploy`
- 404 error on /assets/javascripts/decrypt-contents.js
- but that js is there it is not missing
- gh repo is also private

**Comment by CoinK0in** [comment]
Humm . . . 

Using the exact same versions, same configuration.
Publishing the project via mkdocs module for gh-page with cli  :
```bash
mkdocs gh-deploy --config-file ../mkdocs_poc/mkdocs.yml --remote-branch master
```
I do not reproduce the issue. 

If the script is present, the generation of the JS template is correctly done [in the build process](https://github.com/CoinK0in/mkdocs-encryptcontent-plugin/blob/master/encryptcontent/plugin.py#L350-L363). 
And you should have in the "**md-content**" class div of the material theme the following line:  
`<script defer="" src="/assets/javascripts/decrypt-contents.js" type="text/javascript"></script>`

Do you use a CNAME to rename your site ? 
I am thinking about "CSP policy" or "HTTPS headers" which, by default, can block the loading of resources.
Have you trie to set "**site_url**" values on your Mkdocs config file ? 

Honestly, I don't have any other ideas here :/ 
And i can't check the configuration in case of a "private repo".
(Although I think there is no difference with the public version)

**Comment by JamesRivers** [comment]
Thanks will run through checks and report back

**Comment by JamesRivers** [comment]
Ok much reviewing I have some breadcrumbs that I have been following...  On review of the github page the filename **decrypt-contents.js** is being requested from _/assets/javascripts/decrypt-contents.js_. 

Rather than **/site_dir/assets/javascripts/decrypt-contents.js**

**Comment by CoinK0in** [comment]
Thank you for this additional information. 
I was able to reproduce the problem and I was able to understand that when the site uses a substructure folder, my current configuration does not allow the loading of the decryption script, cause de path is wrong.

I made some tests and modifications, which I published in version [2.0.1](https://github.com/CoinK0in/mkdocs-encryptcontent-plugin/releases/tag/2.0.1).
The script loading path is now based on the `site_url` configuration value, which should be set according to your site subtree. 
[As described here ](https://www.mkdocs.org/user-guide/configuration/#site_url)

I think this time we're good, I'll let you validate that. 
Don't hesitate if you have any feedback, your welcome :)

**Comment by JamesRivers** [comment]
@CoinK0in yes this now works in 2.0.1 - thank you very much for reviewing and sorting.

**Comment by ivanhigueram** [comment]
Hello, sorry for reopening this old issue, but I am having the same problem James had before with the `2.2.1` version. My config looks like this: 

```mkdocs.yml
site_name: site
repo_url: repo_url

theme:
  name: material
  locale: en
  highlightjs: true
  hljs_language: 
    - python
    - R
    - bash

nav:
  - Home: index.md
  - About:
    - 'Contribute to this doc': 'contribute.md'

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - toc:
      permalink: "#"
      separator: "_"

plugins:
  - search: {}
  - encryptcontent:
      title_prefix: '🔒'

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
```

where my `index.md` has the `password` tag. When I run locally everything works fine, but the Github build the asset `decrypt-contents.js` is missing in the index. There is something I am missing here? I am seeing the following in the debugger: 

```html
<script type="text/javascript" src="/assets/javascripts/decrypt-contents.js" defer></script>
```

**Comment by CoinK0in** [comment]
Hi, thanks for checking the closed issues first.

James' problem was related to the use of a subdirectory, as the root of the site (`example.com/foo/`). Before the changes in version 2.0.1, my plugin was not able to adapt to the custom root path. But that shouldn't be the case now.

For the decryption script path to be correct, you must specify this additional path in the `site_url` directive ([described here](https://www.mkdocs.org/user-guide/configuration/#site_url)). You can also use the `site_dir` directive ([described here](https://www.mkdocs.org/user-guide/configuration/#site_dir)) so that the build is generated and hosted correctly via "gh-deploy".

Configuring your website with a modified root path should look like this:
```yaml
site_name: PoC_encryptcontent_plugins
site_url: http://coink0in.github.io/subdir/               # Path is parse and add to the default JS path
site_dir: subdir/                                         # Used to build the site in the "subdir" directory
theme:
  name: material
[...]
```
With this configuration, you should observe a change in the path to the decryption JS script. The path must match your root url.
```html
<script defer="" src="/subdir/assets/javascripts/decrypt-contents.js" type="text/javascript"></script>
```
Tell me if your problem is different (You can open a new issue).
