### ISSUE TITLE
mkdocs build failing

### ISSUE THREAD

**Issue by farhanmasud** [CoinK0in/mkdocs-encryptcontent-plugin#20]
I'm able to serve the local server with mkdocs-encryptcontent-plugin and it works perfectly. But when I'm running ```mkdocs build```, it's failing.

```
ERROR    -  Error reading page
            'index.md': 'NoneType'
            object has no attribute
            'replace'
```
Last message from the traceback - 

```
/venv/lib/python3.8/site-packages/encryptcontent/plugin.py", line 279, in on_page_content
    base_path = page.abs_url.replace(page.url,'')
AttributeError: 'NoneType' object has no attribute 'replace'
```

mkdocs.yml file -

```
theme:
  name: material
plugins:
    - search
    - encryptcontent:
        remember_password: True
        global_password: 'my-password-here'


markdown_extensions:
  - attr_list
  - md_in_html
  - meta
```

Also, just to note, I have nesting of pages inside nav like the following -

```
nav:
  - Main page: main-page.md
    - Sub page 1: sub-page-1.md
    - Sub page 2:
        - Other page 1: other-page-1.md
        - Other page 2: other-page-2.md
```
