### ISSUE TITLE
Entering password doesn't do anything

### ISSUE THREAD

**Issue by zeldridge** [CoinK0in/mkdocs-encryptcontent-plugin#33]
Hi,

So using the plugin, I have the password set globally and when I enter the password it loads the page with a /? at the end of the URL and refreshes the page. No "invalid password" and no access to the site. It doesn't do anything.

How can I fix this? All I have in the plugin settings is "global_password:"

Thanks

**Comment by CoinK0in** [comment]
Hey, 

I do not reproduce the problem with the following configuration and packages :
```shell
python                       3.10.4
mkdocs                       1.3.1
mkdocs-encryptcontent-plugin 2.3.0
mkdocs-material              8.4.2
mkdocs-material-extensions   1.0.3
```

My `mkdocs.yml` configuration file looks like this:
```yaml
site_name: PoC_encryptcontent_plugins
theme:
  name: material
plugins:
  - search: {}
  - encryptcontent:
      global_password: "321"
nav:
  - Home: index.md
  - Tests:
    - Protection: 
      - No Password: "Tests/0-no_password.md"
      - Blank Password: "Tests/1-blank_password.md"
      - With Password: "Tests/2-with_password.md"
      - Diff Password: "Tests/3-diff_password.md"
```

Each file looks like this :
```yaml
# index.md
PoC
```
```yaml
# 0-no_password.md
PoC
```
```yaml
password: 
# 1-blank_password.md
PoC
```
```yaml
password: 321
# 2-with_password.md
PoC
```
```yaml
password: 654
# 3-diff_password.md
PoC
```
----

Could you give me more information about your configuration, such as:
- Python version
- Plugins versions
- Mkdocs version
- Is your site hosted at the root `example.com/` or does your site use a subdirectory `example.com/subdir/` ?
- Do you have any errors in your browser console ?
- Can you give me your mkdocs.yaml configuration file `mkdocs.yaml` ?

-----

Normally when decrypting a page, the page is not reloaded (Like F5, refreshed), it is only JS which modifies the content of the page without reloading it. 

My current assumption is that you are using a root other than "/" to host your site (like example.com/subdir/index.md) and the `site_url` variable in your config does not contain this information.
